### ISSUE TITLE
scss source maps are included in main bundle file

### ISSUE THREAD

**Issue by vultix** [single-spa/single-spa-angular#115]
### Problem
When creating a production build using single-spa-angular for an application that uses scss and has source maps enabled, the outputted main.js file contains the scss source map.

This causes the application styles to grow exponentially, especially when using scss dependencies like angular material.

### Steps to Reproduce

- Follow the [single-spa-angular Angular CLI start guide](https://single-spa.js.org/docs/ecosystem-angular/#angular-cli)
    - `ng new my-app --routing --prefix my-app`
    - `cd my-app`
    - `ng add single-spa-angular`
- Turn on source maps
    - Change line 48 in `angular.json` to `"sourceMap": true,`
- Add some scss
     - Add `$helloWorld: red; body { color: $helloWorld;}` to `src/styles.scss`
- run `npm run build:single-spa`

If you open up the built main.js file and search for `$helloWorld`, you will see that the file includes both the original source and source mapping information for the styles.scss file.

**Comment by joeldenning** [comment]
👍 thanks for the good description on this.

Do you know which webpack loader is used for Angular + Sass applications? Is it https://webpack.js.org/loaders/sass-loader/?

To fix this, we'd want to modify [the webpack config](https://github.com/CanopyTax/single-spa-angular/blob/master/src/webpack/index.ts) to [maybe turn off sass-loader's sourceMap option](https://webpack.js.org/loaders/sass-loader/#sourcemap) in production builds.

The reason this is happening in the first place is probably related to https://github.com/CanopyTax/single-spa-angular/blob/3082db78b504f225b1ee4e6462868eba35c9ca23/src/webpack/index.ts#L26

Angular assumes that css files are loaded in the html file instead of via the js bundle, but in a single-spa application there's only one root html file, instead of one per single-spa application. As a result, we need the css to be loadable via the js bundle alone. Removing the css extract plugin causes the css to be bundled into the js, but yeah we should make sure production builds don't have sourcemaps in them.

Contributions very welcome on this.

**Comment by arturovt** [comment]
Yes, when you set `sourceMap` to the single boolean value in the `angular.json` then it enables source maps for everything possible. If you want to enable source maps for JS and for styles then set it to:
```json
"sourceMap": {
  "scripts": true,
  "styles": false
}
```
