### ISSUE TITLE
Unable to Load Resources from single spa Application

### ISSUE THREAD

**Issue by SwapnilChidrawar** [single-spa/single-spa-angular#129]
Hi,
I am using Single Spa framework ,in which i am using 4 different angular apps. I have images specific to each and every asset folder.I am also using assertUrl to load the images. it works fine on my local but when i deployed these 4 apps as a separate sites in IIS, resources from each and every app, are loading with the root port. ex

app1 as one image angular.png and it is listing on port 4201
root app is listing on port 4200 where app1 is registered. so when i deploy this combination, i am getting image url as http://localhost:4200/dist/assets/angular.png whereas angular.png is part of localhost:4201. 

Please let me know how to fix it.

I am using Angular 8 version and single spa 3.0.1 version

**Comment by SwapnilChidrawar** [comment]
Also when i refresh the page, it says HTTP 404 not found. Suppose I am on localhost:4200/page1 and when i refresh browser it says not found

**Comment by joeldenning** [comment]
Webpack public path is the important concept here. See https://single-spa.js.org/docs/faq/#code-splits and https://webpack.js.org/guides/public-path/#root.

With Angular CLI, you can set the public path for your deployed files with Angular CLI `--deploy-url https://some-url.com/app1`. See more at https://stackoverflow.com/questions/47885451/angular-cli-build-using-base-href-and-deploy-url-to-access-assets-on-cdn. You should not need to set the `base-href` (which is described in that issue), but **should set the deploy url**.

Let me know if that doesn't work. I am closing this issue since I believe this to be more of a documentation problem than a bug in single-spa-angular. I have created https://github.com/single-spa/single-spa.js.org/pull/170 which adds documentation for this so that others hopefully won't struggle with this.

**Comment by SwapnilChidrawar** [comment]
Hi, I have successfully added deploy url option while building app, it successfully shows the proper url but now it says requested resource not found even the resource is present on provided url

**Comment by SwapnilChidrawar** [comment]
Above mentioned issue has been resolved now only problem is when i am refreshing the app it says HTTP Error 404.0 - Not Found for entire app

**Comment by joeldenning** [comment]
This sounds like server configuration issues, or a bug in your deployment script that puts the files in the wrong place. I can't debug why the files on your server aren't loading properly, but it sounds like the single-spa-angular stuff is now resolved.

**Comment by SwapnilChidrawar** [comment]
Everything has been resolved now.. Thanks for your help
