### ISSUE TITLE
Uncaught TypeError: Cannot read property 'injector' of undefined

### ISSUE THREAD

**Issue by SwapnilChidrawar** [single-spa/single-spa-angular#131]
Hi.. 

I am trying to integrate the existing angular version 8 application to single spa. For that I have also followed the steps provided by the official documentation. After doing all these stuff, when i am trying to start my microfront end app, system is giving me a wearied error that is **Cannot read property injector of undefined.**  I looked around this issue and I found same issue encountered previously [65](https://github.com/single-spa/single-spa-angular/issues/65).

As per that, I have also added few things like adding APP_BASE_HREF and all but still I did not get any success on this. Here just like previous bug that is bug no 65, application is not mounting the module and hence it returns this undefined injector error.

![error](https://user-images.githubusercontent.com/17702699/74800848-ccd47a00-52fa-11ea-9c04-496e6c30f8a0.PNG)

This is the error that I have encountered.

![code](https://user-images.githubusercontent.com/17702699/74800871-dc53c300-52fa-11ea-855d-02d55a5b2a91.PNG)

In this above code, I am getting that undefined error at line no 100, so I also checked whether it is getting mounted or not on line no 90, it is not getting called.

Any help on this will be appreciated.

Thanks

**Comment by SwapnilChidrawar** [comment]
Somehow I managed to fix this error. but now new error is generated. **died in status LOADING_SOURCE_CODE: "does not export an unmount function or array of functions"** There was one error related to this but specific to react application not with the angular. [1](https://github.com/joeldenning/single-spa-es5-angularjs/issues/1)

**Comment by sonalmusale22** [comment]
I am also facing the same issue. Could you please help.

**Comment by joeldenning** [comment]
> Cannot read property injector of undefined

When single-spa fails to mount an application, it attempts to unmount it immediately. The `Cannot read property 'injector' of undefined` error is related to it failing to immediately unmount after the failed mount.

The fix is to solve the problem causing it to fail to mount in the first place. In your first post, that is the `ServiceError: Unexpected content type`. You should debug that problem.

> died in status LOADING_SOURCE_CODE: "does not export an unmount function or array of functions"

Are you using SystemJS? Or not. If you are using SystemJS, try running `await System.import('appName')` in the browser console. Note that the returned object is missing the single-spa lifecycles (bootstrap, mount, unmount). You need to modify your SystemJS an webpack configuration until `System.import()` actually resolves with the correct object.

> I am also facing the same issue. Could you please help.

@sonalmusale22 please read my first comment here. The error about the injector is an effect of a failed mount. It is unlikely that your application is failing to mount for the same reasons as @SwapnilChidrawar. You need to debug the failed mount error in order to fix this.

I am closing this issue because it does not appear to be a bug in single-spa or single-spa-angular. Instead, it appears to be a problem with the systemjs or webpack configuration for your projects
