### ISSUE TITLE
Angular UI Router

### ISSUE THREAD

**Issue by dmeagor** [single-spa/single-spa-angular#177]
Hi,

I see that single spa works with UI router on AngularJS.  Are there any issues integrating to UI Router with Angular 8/9?  Looks like the documentation refers to the inbuilt router.

**Comment by arturovt** [comment]
Hey @dmeagor 
It's been 7 months since this issue was opened and no one commented here thus I can take a look if it works correctly.

What do you mean by `Are there any issues integrating to UI Router with Angular 8/9?`?

* Does it mean that you have 2 coexisting microfrontends: the first microfrontend uses AngularJS and the second one uses Angular 8/9?
* Does it mean that you've got 1 microfrontend written in AngularJS but components are written in new Angular and downgraded via `ngUpgrade`?

**Comment by arturovt** [comment]
Hey @dmeagor 

It's been a long time since this issue has been inactive. I really wish to help you but unfortunately I didn't get enough information.

Feel free to re-open it if you have something to add.
