### ISSUE TITLE
canDeactivate is not invoked when changing single-spa apps with browser back/forward buttons

### ISSUE THREAD

**Issue by oskar-szwajkowski** [single-spa/single-spa-angular#184]
### Demonstration

Hello, I have run into bug (at least I think it is one) regarding invoking `canDeactivate` guards while changing single-spa applications with back / forward browser buttons.

Steps to reproduce:

1. Create parent single-spa application
2. Create child single-spa application with `canDeactivate` guard, can pop up confirm button or console.log, doesn't matter
3. Navigate to child app from parent, using angular's router navigation
4. Press 'back' browser button on child app, so we are moved back to parent app route
5. `canDeactivate` guard hasn't been called between apps transitions using browser buttons

### Expected Behavior
`canDeactivate` guard is called, so we can invoke changing route prevention logic

### Actual Behavior
`canDeactivate` is not called when transitioning between single-spa apps using browser buttons, however it does work within routes within single application

**Comment by arturovt** [comment]
Provide a _minimal reproducible example_, please.

**Comment by arturovt** [comment]
Any progress on this?

**Comment by oskar-szwajkowski** [comment]
> Any progress on this?

Preparing reproduction repo ATM

**Comment by oskar-szwajkowski** [comment]
Repo that reproduces issue, with instructions in README.md:

[Repo](https://github.com/oskar-szwajkowski/single-spa-angular-issue-184)

**Comment by arturovt** [comment]
Thanks! I will have a look asap.

**Comment by arturovt** [comment]
Hey Oskar! Thanks for reproduction, that is appreciatable!

I was able to reproduce your issue and the problem is that `unmount()` for the child app is called before the `popstate` is dispatched.

So there are 2 possible ways to navigate from `/page-child` to `/parent-1`:
1) To click on the link `<a href="/parent-1"` which calls `router.navigateByUrl(...)`, notifies router that he has to check guards and then do `replaceState` (if can deactivate checks are passed).
2) Click on the back button, thus `single-spa` will dispatch `popstate` event. The router will be notified that `popstate` has been dispatched and it should run can deactivate checks.

The problem is that navigation from `/page-child` to `/parent-1` is navigation between 2 apps which of course should destroy the previous app and create a new one. Thus `single-spa` just calls `unmount()` and the `/page-child` app gets destroyed immediately w/o any checks.

@joeldenning any thoughts?

**Comment by joeldenning** [comment]
> Click on the back button, thus single-spa will dispatch popstate event.

The browser fires this PopStateEvent, not single-spa. Back/Forward button clicks trigger browser PopStateEvents

> The problem is that navigation from /page-child to /parent-1 is navigation between 2 apps which of course should destroy the previous app and create a new one. Thus single-spa just calls unmount() and the /page-child app gets destroyed immediately w/o any checks.

Interesting, thanks for the good description. I'm not very familiar with Angular's CanDeactivate interface, but just read about it at https://angular.io/api/router/CanDeactivate. I have a few questions about it that might shed light on options for single-spa-angular applications:

1. The docs refer to "canceling navigation." Does this involve calling `history.replaceState()` back to the old url?
2. Do the canDeactivate checks occur synchronously as a result of navigateByUrl? Or is it queued up in a future microtask/task of the event loop?
3. Is there any way to manually tell the router to run canDeactivate checks for a URL?

**Comment by arturovt** [comment]
2. Navigation is always asynchronous itself:

https://github.com/angular/angular/blob/a62c1c441c67616ce5eacc7e8dcfe169316d4552/packages/router/src/router.ts#L497

And can deactivate checks behaviour only relies on the return value of `canDeactivate()` method since it can return `boolean | Observable<boolean> | Promise<boolean>`:
```ts
canDeactivate() { return true } // sync
canDeactivate() { return of(true) } // sync
async canDeactivate() // will be always async...
```

3. No. Guards are a part of the navigation lifecycle, so it should call `scheduleNavigation` to run all lifecycles.

**Comment by joeldenning** [comment]
Hmm one option might be to add some logic to single-spa-angular's `unmount` function to wait for the scheduled navigation to finish before calling `destroy()`?

https://github.com/single-spa/single-spa-angular/blob/389a16cb186ed5fd975199ff2e4670084c47a84f/src/src/single-spa-angular.ts#L157

https://github.com/single-spa/single-spa-angular/blob/389a16cb186ed5fd975199ff2e4670084c47a84f/src/src/single-spa-angular.ts#L161

https://github.com/single-spa/single-spa-angular/blob/389a16cb186ed5fd975199ff2e4670084c47a84f/src/src/single-spa-angular.ts#L197

If there's a way we can wait for the scheduled navigation to finish, we could perhaps detect whether the routing was canceled and then skip destroying the app if so?

**Comment by arturovt** [comment]
The problem is that if can deactivate checks are not passed then the app shouldn't be unmounted, but it still will. Thus it's an extra work w/o purpose.

**Comment by joeldenning** [comment]
By calling `pushState` before doing the canDeactivate checks, Angular makes the navigation occur. There is no such thing as canceling navigation on a browser level - that's an Angular construct that doesn't fit how browsers work.

My proposal is a workaround to Angular's odd behavior - since we can't prevent the initial pushState from happening, single-spa will reroute. That reroute will result in the single-spa-angular `unmount` function being called. My idea is to skip destroying the app during single-spa's unmount lifecycle if the canDeactivate checks indicate that the app should not be unmounted. My thought is that once Angular determines that the navigation should be canceled that it presumably would call `history.replaceState(oldState, oldTitle, oldUrl)`, which would then trigger a second single-spa reroute. During the second single-spa reroute, the `mount` lifecycle would be called, which we could also skip since the application is already mounted.

^ This workaround isn't perfect, and I'm open to other ideas. The root problem here is that Angular tells the browser to navigate before it's sure that it wants to navigate.

**Comment by arturovt** [comment]
> The root problem here is that Angular tells the browser to navigate before it's sure that it wants to navigate.

Not sure. As I said `unmount()` is called _before_ the `popstate` is fired. Angular does not even have time to run the check. Angular calls `replaceState` after checking guards.

**Comment by joeldenning** [comment]
> Not sure. As I said unmount() is called before the popstate is fired. Angular does not even have time to run the check. Angular calls replaceState before and after checking guards. But it calls replaceState of course after getting popstate event.

`popstate` fires **after** navigation, and unmount is called **during** navigation. The way that Angular is telling the browser to navigate is by calling pushState/replaceState, which is what triggers the single-spa reroute function that results in unmount being called.

**Comment by arturovt** [comment]
Is `pushState` or `replaceState` called when clicking "back" button?

**Comment by joeldenning** [comment]
No they are not, good catch. Thinking this through again, I realize I have been assuming this is during normal navigation, not during back/forward buttons. This means that much of what I said above was based on bad assumptions and is wrong.

In regards to back/forward buttons, there is no way to tell a browser to "prevent" the back/forward navigation from occurring. Angular's canDeactivate approach is doing so in a false way - it lets the URL change and then changes the URL back to what it was before. It's not using browser APIs to cancel the navigation, but instead is assuming that it is the singular router on the page with full control over what happens on the page.

I don't think we'll be able to support this case in single-spa. The more I learn about Angular Router, the less I like it - there are very good security and accessibility reasons why canceling a user's back/forward button press is disallowed by browsers. As such, is unreasonable for a single-spa application to expect to be able to do so.

**Comment by oskar-szwajkowski** [comment]
I'm not that much into angular's internals, but from what you are speaking, I have 2 questions then.

1. If angular does 'back' and 'forward' browser buttons navigation in 'false' way as you said, how are we able to display window.prompt before navigating with browser button, and never reach different url? Does the url change happens so fast that we only can spot it by subscribing to some kinds of events, never in address bar directly?

2. If single-spa-angular had not only 'client' implementation, but also 'microfrontend orchestrator' implementation done purely in angular, and using its API, wouldn't this solution be able to proxy angular router and handle those 'back' and 'forward' buttons between apps, in same way as within one single-spa app which works?

**Comment by joeldenning** [comment]
> If angular does 'back' and 'forward' browser buttons navigation in 'false' way as you said, how are we able to display window.prompt before navigating with browser button, and never reach different url? Does the url change happens so fast that we only can spot it by subscribing to some kinds of events, never in address bar directly?

If the page is "unloading," you can use the [`beforeunload` event](https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event) to do the prompt and then call `preventDefault()` on that event if you don't want to let them leave.

However, when navigating between routes in an SPA, there is no `beforeunload` event since the page is not unloading/reloading. As far as I know, there is no way to prevent the URL from changing when the user presses the back/forward buttons and the page is not unloading. If there is a way that I'm unaware of, I'd love to learn it!

> If single-spa-angular had not only 'client' implementation, but also 'microfrontend orchestrator' implementation done purely in angular, and using its API, wouldn't this solution be able to proxy angular router (or do something like uber-router) and handle those 'back' and 'forward' buttons between apps, in same way as within one single-spa app which works?

I don't fully understand what you're proposing here, but will do my best to answer. My understanding is that if you have separate angular microfrontends that each call `platformBrowserDynamic().bootstrapModule()`, that there is no way to get that working with canDeactivate (even if your "orchestrator" is also angular). My understanding is that the only way to get canDeactivate working for back button clicks is to have a single angular app (only one call to `platformBrowserDynamic().bootstrapModule()`). Happy to be shown otherwise - am just sharing based on my limited understanding of Angular Router's scheduleNavigation function and the canDeactivate mechanism.
