### ISSUE TITLE
Lazy-loaded modules fail to load in --prod mode: "TypeError: Cannot read property 'call' of undefined"

### ISSUE THREAD

**Issue by matt-gold** [single-spa/single-spa-angular#218]
If you have more than one single-spa-angular application running in --prod mode, only one of the applications will be able to access its lazy-loaded modules. Accessing lazy-loaded modules subsequently from other single-spa-angular apps will fail with "TypeError: Cannot read property 'call' of undefined".

### Demonstration
*MINIMAL DEMO*
https://github.com/matt-gold/coexisting-angular-microfrontends

*STEPS TO REPRODUCE*
- Create a single-spa application with two different single-spa-angular apps (e.g. app1 and app2).
- Add a lazy-loaded route to each angular app (e.g. /app1/lazy and /app2/lazy).
- Run the angular apps with --optimization=true (this is the default when using --prod flag).
- Attempt to navigate to load both of the lazy-loaded routes in a single session without a hard browser-refresh (e.g. via router-link)

### Expected Behavior
Lazy loaded modules should load without issue.

### Actual Behavior
The second lazy module you attempt to load will cause a fatal error.
`"TypeError: Cannot read property 'call' of undefined"`

**Comment by arturovt** [comment]
Thanks for reproduction. I will try to have a look this evening.

**Comment by jimmyhdolores** [comment]
Any solution for this problem? that happens to me too

**Comment by amilaI** [comment]
Same here!

**Comment by amilaI** [comment]
Any solution so far ?

**Comment by arturovt** [comment]
Sorry for delay guys, I was stuck at work...

I was able to reproduce it. Thanks again @matt-gold for providing reproductions, it is appreciated! :heart: 

The quick fix that I've done:
```js
// app1/extra-webpack.config.js

const singleSpaAngularWebpack = require('single-spa-angular/lib/webpack')
  .default;

module.exports = (angularWebpackConfig, options) => {
  const singleSpaWebpackConfig = singleSpaAngularWebpack(
    angularWebpackConfig,
    options
  );

  singleSpaWebpackConfig.output.library = 'coolApp1'; // <!--- NOTICE THIS

  // Feel free to modify this webpack config however you'd like to
  return singleSpaWebpackConfig;
};
```

The problem is that there is a hardcoded value `app3` for the library name which forces Webpack to load chunks in the wrong way.

What Webpack does when you click the link is:

* resolve chunk id and URL to load it from (in our case it's `/1.js`)
* load chunk
* cache the chunk by adding it to `window` property
  * `window['webpackJsonp' + config.output.library]`
  * in our case it's `window.webpackJsonpapp3` (because `app3` is hardcoded)
* it caches it by doing:
  ```js
  window.webpackJsonpapp3.push(
    [1], // chunk id
    {
      [$concatenated module factory stored by hashed id$]: function(module, exports, require) { ... }
    }
  )
  ```

This error doesn't occur immediately when we go to app1 because there is no `window.webpackJsonpapp3` property yet. It's created when the first lazy module is loaded, in our case it's `app1/lazy`.

After that when we go to `app2` everything is still okay. Then we click the button and go to `app2/lazy` and it fails with `Cannot read property call of undefined`, because
* Webpack goes to `window.webpackJsonpapp3` and looks for the chunk with id `1` (`app2` has the same chunk id as `app1`)
* it sees that chunk with such id (it's `app1`'s chunk)
* it tries to access the module factory by hashed id of the `app2`'s module, but it doesn't exist there thus `undefined`.

---

I see there is an existing issue regarding hardcoded `app3`. The PR hasn't been made yet, I guess I'm gonna look at it.

IMO the `output.library` should equal the project name (defined in angular.json).

**Comment by jimmyhdolores** [comment]
Thanks for sharing @arturovt  , well in my case I solved it by adding singleSpaWebpackConfig.output.library and adding the public path, save it in a file called "set-public-path" and it contained

```javascript
import {setPublicPath} from 'systemjs-webpack-interop';
setPublicPath ('@ demo/login');
```

and I call this file inside "main.single-spa.ts"

```javascript
import "./set-public-path";
```

In this way it does not throw the error until now, I will continue testing, thanks for your time.

**Comment by amilaI** [comment]
> Sorry for delay guys, I was stuck at work...
> 
> I was able to reproduce it. Thanks again @matt-gold for providing reproductions, it is appreciated! ❤️
> 
> The quick fix that I've done:
> 
> ```js
> // app1/extra-webpack.config.js
> 
> const singleSpaAngularWebpack = require('single-spa-angular/lib/webpack')
>   .default;
> 
> module.exports = (angularWebpackConfig, options) => {
>   const singleSpaWebpackConfig = singleSpaAngularWebpack(
>     angularWebpackConfig,
>     options
>   );
> 
>   singleSpaWebpackConfig.output.library = 'coolApp1'; // <!--- NOTICE THIS
> 
>   // Feel free to modify this webpack config however you'd like to
>   return singleSpaWebpackConfig;
> };
> ```
> 
> The problem is that there is a hardcoded value `app3` for the library name which forces Webpack to load chunks in the wrong way.
> 
> What Webpack does when you click the link is:
> 
> * resolve chunk id and URL to load it from (in our case it's `/1.js`)
> * load chunk
> * cache the chunk by adding it to `window` property
>   
>   * `window['webpackJsonp' + config.output.library]`
>   * in our case it's `window.webpackJsonpapp3` (because `app3` is hardcoded)
> * it caches it by doing:
>   ```js
>   window.webpackJsonpapp3.push(
>     [1], // chunk id
>     {
>       [$concatenated module factory stored by hashed id$]: function(module, exports, require) { ... }
>     }
>   )
>   ```
> 
> This error doesn't occur immediately when we go to app1 because there is no `window.webpackJsonpapp3` property yet. It's created when the first lazy module is loaded, in our case it's `app1/lazy`.
> 
> After that when we go to `app2` everything is still okay. Then we click the button and go to `app2/lazy` and it fails with `Cannot read property call of undefined`, because
> 
> * Webpack goes to `window.webpackJsonpapp3` and looks for the chunk with id `1` (`app2` has the same chunk id as `app1`)
> * it sees that chunk with such id (it's `app1`'s chunk)
> * it tries to access the module factory by hashed id of the `app2`'s module, but it doesn't exist there thus `undefined`.
> 
> I see there is an existing issue regarding hardcoded `app3`. The PR hasn't been made yet, I guess I'm gonna look at it.
> 
> IMO the `output.library` should equal the project name (defined in angular.json).

Thanks @arturovt for the fix. much appreciated!

**Comment by arturovt** [comment]
Hey @matt-gold 
Can this issue be closed?

**Comment by arturovt** [comment]
Was talking to Matt in Slack, this can be closed.
