### ISSUE TITLE
Cannot create a new Angular app using create-single-spa

### ISSUE THREAD

**Issue by jethas-bennettjones** [single-spa/single-spa-angular#270]
### Demonstration

Here are the options that I use:
![Capture](https://user-images.githubusercontent.com/62298251/92637926-c148a080-f296-11ea-8e9b-b8899537df1a.PNG)
![Capture](https://user-images.githubusercontent.com/62298251/92638044-ec32f480-f296-11ea-8092-23082da0a313.PNG)

### Expected Behaviour
Application can be build and run without issue

### Actual Behaviour
![Capture](https://user-images.githubusercontent.com/62298251/92638109-08369600-f297-11ea-8c8a-2a68994cea88.PNG)

**Comment by filoxo** [comment]
(Also, I don't think this is an issue for create-single-spa since the Angular code was generated successfully. I'm more inclined to suspect that the Angular generator didn't work correctly when installing single-spa-angular. The reason I think this is because the start script is missing the app name, which create-single-spa doesn't add. I could be wrong though.)

**Comment by jethas-bennettjones** [comment]
Hi @filoxo. I had initially tried it with the the latest version but it didn't work so that's when I switched to an older version.
I'll try it again and see if what you're saying about the naming is the issue.

**Comment by jethas-bennettjones** [comment]
I tried this with the latest version and it looks like it's been resolved.
