### ISSUE TITLE
How to communicate between parent and child using "Rxjs" observable approach with Angular-cli-spa

### ISSUE THREAD

**Issue by 3gwebtrain** [single-spa/single-spa-angular#277]
From my parent application i required to connect and send some flags. at present I use the approach as:

```
sendMessage() {
    const event = new Event('toggleClock');
    window.dispatchEvent(event);
  }
```

it works. but my client is not accepting since we use the window object, which is open for all. I am trying to find a way to communicate using "rxjs" observable. in case of "angular-cli" with "single-spa" I am not find any solution / tutorial or examples. please need the help here.

I am interested in this approach:

> Export shared state from the public interface of your microfrontend so that libraries can import it. For values that change over time, Observables (RxJS docs) can be useful. Create a ReplaySubject so that you can push new values out to all subscribers at any time.

here is my sample code base: [https://github.com/3gwebtrain/single-spa](https://github.com/3gwebtrain/single-spa)

Thanks in advance.

**Comment by arturovt** [comment]
I don't think it's possible to communicate between applications w/o using `window` object. Saying this just because I googled a lot of examples/articles regarding that and all of them use the `window` object. Even the `vue-bus` or other related packages use the `window` object.

On my last job we wrote a simple small package which had an API something similar to Node's EventEmitter. Multiple applications could subscribe and publish events to appropriate channels, something like:
```ts
export class SidebarComponent {
  sidebarOpened = true;

  constructor(private messageService: MessageService) {}

  ngOnInit() {
    this.messageService
      .channel('toggleSidebar')
      .pipe(takeUntil(this.destroy$))
      .subscribe(() => {
        this.toggleSidebar();
      });
  }

  toggleSidebar() {
    this.sidebarOpened = !this.sidebarOpened;
    this.messageService.channel('sidebarHasBeenToggled').publish();
  }
}
```

Under the hood there was a simple `Map<channelName, Subject>`, which allowed to multicast events between multiple applications, but it was also exposed to `window`.

**Comment by joeldenning** [comment]
You can import/export rxjs Observables, Subjects, etc between microfrontends via [cross microfrontend imports](https://single-spa.js.org/docs/recommended-setup#cross-microfrontend-imports)

Additionally, it's possible to share the same instance of the rxjs library between microfrontends is possible, by marking `rxjs` and its operators as webpack externals. More info at https://single-spa.js.org/docs/recommended-setup#sharing-with-import-maps.

The react-microfrontends example shows this:

https://github.com/react-microfrontends/people/blob/8aed06826f6f74af80de06113924d62d0b8a51c0/webpack.config.js#L31

https://github.com/react-microfrontends/shared-dependencies/blob/147b2811f1eec085a0e13f002abd4bc2dad74a9b/importmap.json#L6

**Comment by arturovt** [comment]
Closing since the guide has been added to single-spa docs.
