### ISSUE TITLE
Add fesm5 Angular Package Format (APF) builds

### ISSUE THREAD

**Issue by petermikitsh** [single-spa/single-spa-angular#302]
### Description of Proposed Feature

From https://unpkg.com/browse/single-spa-angular@4.7.0/package.json, the following output formats are produced:

- main
- module
- es2015
- esm2015
- fesm2015

### In what way would you use it?

I am using single-spa-angular with an Ivy-enabled Angular app. Part of switching to ivy requires running `ngcc` postinstall (to make node_modules are ivy-compatible-- not only third party modules, but core angular packages as well). 

In my project, webpack is requiring format `fesm5` for all core angular modules, but `fesm2015` for single-spa-angular. So I have to build for both targets, resulting in some extra cpu cycles.

By adding a `fesm5` build I could switch my postinstall command from `ngcc --properties fesm5 fesm2015` to `ngcc --properties fesm5`.

Also, this applies to the other entry points, including:

- single-spa-angular/internals
- single-spa-angular/elements
- single-spa-angular/parcel

**Comment by arturovt** [comment]
@petermikitsh I don't think it's an issue since Angular officially dropped fesm5 and esm5.

> esm5 and fesm5 format is no longer distributed in Angular's npm packages e.g. @angular/core
If you are not using Angular CLI to build your application or library, and you need to be able to build es5 artifacts, then you will need to downlevel the distributed Angular code to es5 on your own.
Angular CLI will automatically downlevel the code to es5 if differential loading is enabled in the Angular project, so no action is required from Angular CLI users.

**Comment by arturovt** [comment]
Closing as "not an issue".
