### ISSUE TITLE
How to fix the `scope` issue between parent and child application?

### ISSUE THREAD

**Issue by 3gwebtrain** [single-spa/single-spa-angular#318]
In my wrapper application I made a change and downloading the `jquery` it is downloading in windows scope. in my child app, I declared the `external` configuration as follows:

```
const singleSpaAngularWebpack = require("single-spa-angular/lib/webpack")
  .default;

module.exports = (angularWebpackConfig, options) => {
  const singleSpaWebpackConfig = singleSpaAngularWebpack(
    angularWebpackConfig,
    options
  );

  singleSpaWebpackConfig.externals = {
    jquery: ["jQuery"],
  };
  // Feel free to modify this webpack config however you'd like to
  return {
    ...singleSpaWebpackConfig,
  };
};

```

In my child application I am trying to use the `jquery` like this:

```
import { Component, OnInit } from "@angular/core";
declare const $: any;

@Component({
  selector: "child1-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"],
})
export class AppComponent implements OnInit {
  title = "child1";

  constructor() {
    $("h1").css({ border: "2px solid green" }); //issue is here.
  }

  ngOnInit() {
    window.addEventListener("toggleClock", () => {
      console.log(" i am hearing from parent");
    });
  }
}

```

Now instead of my child `h1` tag bordered, it's border to `parent` ( host ) applications `h1` tag. how can i fix this `scope` issue. But I do not getting any error. all works fine. but the child app apply the values to parent inside of it's own scrope. I have tried like this:

`$("child1-root h1").css({ border: "2px solid green" });` adding the root, but not working. how to fix this? please any one suggest me the correct way?

it's basically trying to share single `externals` to multiple apps.
Thanks in advance.

**Comment by joeldenning** [comment]
Hi @3gwebtrain - jquery is generally not encouraged for applying CSS styles in Angular for a variety of reasons. If you'd like to use it, you need to ensure that the CSS selector passed to jquery is unique to the component instance.

Here's a selector that is unique to the component, but would still have problems if you render the same component twice (two instances):

```js
$("child1-root h1").css({ border: "2px solid green" });
```

I'm closing this as this is not related to single-spa-angular - it's related to using jquery where you shouldn't, since jquery is not aware of Angular components and component instances.
