### ISSUE TITLE
"ng add single-spa-angular" is failing on Angular 11.1.0

### ISSUE THREAD

**Issue by aggiustino** [single-spa/single-spa-angular#332]
Running `ng add single-spa-angular` on a freshly created Angular App using Angular CLI, is causing an exception:

```
An unhandled exception occurred: Cannot find module '@schematics/angular/utility/config'
Require stack:
- node_modules/single-spa-angular/schematics/ng-add/index.js
- node_modules/@angular-devkit/schematics/tools/export-ref.js
- node_modules/@angular-devkit/schematics/tools/index.js
- node_modules/@angular/cli/utilities/json-schema.js
- node_modules/@angular/cli/models/command-runner.js
- node_modules/@angular/cli/lib/cli/index.js
- node_modules/@angular/cli/lib/init.js
- node_modules/@angular/cli/bin/ng
```

`@schematics/angular/utility/config` has been moved since `@schematics/angular@11.0.1`.

**Comment by joeldenning** [comment]
cc @arturovt.

@aggiustino do you know where `utility/config` was moved to?

**Comment by arturovt** [comment]
I’ll have a look tomorrow.

**Comment by aggiustino** [comment]
@joeldenning This have been moved from `packages/schematics/angular/utility/config.ts` → `packages/schematics/angular/migrations/update-6/config.ts`.

This is the commit: https://github.com/angular/angular-cli/commit/7e25cedd4b0a7f38de5d46dc4cbbecfd8da524a8?branch=7e25cedd4b0a7f38de5d46dc4cbbecfd8da524a8

**Comment by arturovt** [comment]
Honestly saying they do too much refactoring each patch and minor release.

I didn't re-write a lot of code since that would break backward compatibility with previous versions. They re-wrote schematics in Angular 11 and the "direct" workspace access is deprecated right now. This will require a lot of refactoring.

I guess I'll do that refactoring with Angular 12 since 11 still keeps backward compatibility.

**Comment by joeldenning** [comment]
Fix released in https://github.com/single-spa/single-spa-angular/releases/tag/v4.9.2
