### ISSUE TITLE
ERROR in getInternalNameOfClass() called on a non-ES5 class: expected SingleSpaPlatformLocation to have an inner class declaration

### ISSUE THREAD

**Issue by engg-aruny** [single-spa/single-spa-angular#346]
**When running with tsconfig.json -> "target": "es2015"** -> It compiling everything

**When running with tsconfig.json -> "target": "es5"**  ->  Error: Error on worker #2: Error: getInternalNameOfClass() called on a non-ES5 class: expected SingleSpaPlatformLocation to have an inner class declaration

Here is package.json, I have.

![image](https://user-images.githubusercontent.com/12406373/112333533-b14b5800-8ce0-11eb-9d7c-4cab45fcb4e3.png)

### Expected Behavior

It should work with both "target": "es2015"** and "target": "es5"**

### Actual Behavior
**When running with tsconfig.json -> "target": "es5"**  - Error as above.

Please help, need a prompt response.

**Comment by joeldenning** [comment]
The single-spa-angular library does not publish es5 bundles to npm. See https://www.jsdelivr.com/package/npm/single-spa-angular:

![image](https://user-images.githubusercontent.com/5524384/112396386-a7682b80-8cc5-11eb-8c8c-de7612cd8b40.png)

Notice how `fesm2015` and `esm2015` are there, but `fes5` and `es5` are not.

The reason that single-spa-angular does not publish es5 bundles anymore is because Angular itself no longer publishes es5 bundles. See related https://github.com/single-spa/single-spa-angular/issues/312.

If you want an es5 version of single-spa-angular, you'll need to compile it yourself. I know how to do that with raw webpack configuration, but not through angular cli + angular compiler which are more complex. There is likely a way to do it via angular.json, but if not it is definitely possible via extra-webpack config. However, that's not something I can help you with, as I don't know angular very well.

Closing this as single-spa-angular intentionally does not publish es5 bundles, as described above. Single-spa-angular does work in IE11 if you compile it to es5 first.

**Comment by engg-aruny** [comment]
Thank You prompt response.
