### ISSUE TITLE
change detection not triggered upon values emitted from a shared observable

### ISSUE THREAD

**Issue by edenilan** [single-spa/single-spa-angular#360]
### Demonstration
I forked the "coexisting-angular-microfrontends" example repo and added a minimal reproduction of the issue: https://github.com/edenilan/coexisting-angular-microfrontends

The navbar application now exposes a `heartbeat$` Observable, and a `restartHeartbeat` function
- `heartbeat$` is imported in both App1 and App2, and displayed in their template.
- `restartHeartbeat` is invoked on init of App1 only

(`heartbeat$` starts emitting values only after the first call to `restartHeartbeat`)

Steps to reproduce:
1. run these apps locally: navbar, app1, app2 (and add import-map overrides in the demo http://coexisting-angular-microfrontends.surge.sh/) 
2. go to App 1
3. go to App 2 (via the navbar)

### Expected Behavior
after step 3 we should see the heartbeat updating in App 2
### Actual Behavior
- the heartbeat is not updated in the view of App 2
- we see the updates only when clicking the "Click Me!" button (which triggers change detection)

**Comment by arturovt** [comment]
Well, I know that might look weird but the behavior is obvious. Let me bring some context in it.

There are 2 apps that fork different zones. DOM timers, event listeners and other patched asynchronous API remembers the zone they were created (added or invoked) in. E.g.:

```js
import 'zone.js';

const zone = Zone.root.fork({
  name: 'superTestingZone',
});

const capture = false;

zone.run(() => {
  document.addEventListener('click', () => {
    console.log(Zone.current); // superTestingZone
  }, { capture });
});

zone.parent.run(() => {
  document.dispatchEvent(new Event('click'));
});

// This is how zone.js remembers the current execution context
const [task] = document[Zone.__symbol__('click') + capture.toString()];

console.log(task._zone.name); // superTestingZone
```

App1 calls `resetHeartbeat()` which emits the value, the `switchMap` unsubscribes from the previous `timer` and subscribes to the new one, the `timer` uses `AsyncAction` under the hood which uses `setInterval`. The `resetHearbeat()` is called when the current execution context is `Zone.current -> app1`.

That's why the hearbeat is updated inside the app1 because `setInterval` triggers `invokeTask()` which triggers app1's zone lifecycle hooks and its `ApplicationRef` calls `tick()` (because `setInterval` remembers the context by creating `ZoneTask` which references app1's zone).

When you go to app2 the `heartbeat$` still emit values but the value is not updated inside the template because `ApplicationRef` doesn't call `tick()`. It doesn't call `tick()` because `setInterval` keeps triggering app1's zone (which was destroyed).

When you're using such global or shared variables be sure to "notify" the current app's zone. This can be through some custom operator, e.g.:
```ts
function enterZone<T>(ngZone: NgZone) {
  return (source: Observable<T>) =>
    new Observable((observer) =>
      source.subscribe({
        next: (value: T) => ngZone.run(() => observer.next(value)),
        error: (error) => ngZone.run(() => observer.error(error)),
        complete: () => ngZone.run(() => observer.complete()),
      })
    );
}

@Component({
  selector: "app2-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"],
})
export class AppComponent {
  title = "app2";
  heartbeat$ = heartbeat$.pipe(enterZone(this.ngZone));

  constructor(private ngZone: NgZone) {}
```

:point_down: 

![image](https://user-images.githubusercontent.com/7337691/117586684-5f408380-b122-11eb-9c4a-36ca80a614c2.png)

**Comment by arturovt** [comment]
No, it shouldn't. We're keeping this package dependency-less. The Angular team states that change detection is always the responsibility of developers.

Tho not all projects are sharing global subjects. That means they would import the package they don't need, increasing the bundle size.

> devs can easily forget to add it

Well, you can expose a function (except subject) which takes the `ngZone` argument:

```ts
// Except of this:
export const heartbeat$ = restartSubject.pipe(
    switchMap(() => timer(0, 1000)),
    share()
);

// Do this:
const heartbeat$ = restartSubject.pipe(
    switchMap(() => timer(0, 1000)),
    share()
);

function enterZone<T>(ngZone: NgZone) { ... }

export function getHeartbeat(ngZone: NgZone) {
  return heartbeat$.pipe(enterZone(ngZone));
}
```

> The behavior I was expecting feels to me like something that should come "out of the box" thanks to single-spa-angular

The single-spa-angular acts as a bridge between the single-spa package and the Angular application. It's not and shouldn't be responsible for the zone.js behaviour since it also supports zone-less mode (where the zone.js is not imported at all and nooped through `CompilerOptions` when bootstrapping an app).

**Comment by edenilan** [comment]
Alright, fair enough - thanks @arturovt  :)
Adding the zone-rxjs patch sounds like a good fit for our "zone-full" applications - so we'll just add the import ourselves.
From your experience, might this patch conflict with anything else in `single-spa-angular`?

**Comment by arturovt** [comment]
Well, personally, I hate zone.js for what it's doing :D

I'm working in zone-less environments most often where rendering time matters. Adding rxjs patch might cause some weird behaviour in the future again with different execution contexts; it will be complicated to find a root cause.

I wouldn't rely on that patch. It'd be clearer from the technical perspective to rely on the custom operator where the observable will emit the value in the app's execution context where it has been subscribed.

**Comment by edenilan** [comment]
Thanks again @arturovt, guess I can close this issue as there are 2 available solutions
