### ISSUE TITLE
How to import module from another project

### ISSUE THREAD

**Issue by llinq** [single-spa/single-spa-angular#382]
### Question
Please help me,

**I have 3 applications:**
- **root-js**: Contains single-spa startup settings and routes.
- **core:** Contains navigation layout and modules/pipes/services to be reused in other applications.
- **analise-compras**: Main application where the user interacts, application must be able to reuse modules exported by core.

I made the module export and importmap settings but I'm still getting the following error:

![image](https://user-images.githubusercontent.com/26715721/128440158-8f4edbf8-161c-4d2e-9327-76a329c6e412.png)

root-js importmap
<pre>
  <script type="systemjs-importmap">
    {
      "imports": {
        "@mtcorp/root-config": "//localhost:9000/mtcorp-root-config.js",

        "@mtcorp/core/navigation": "http://localhost:4200/main.js", 

        "@mtcorp/core": "http://localhost:4200/main.js",
        
        "@mtcorp/abastecimento/analise-compra": "http://localhost:4201/main.js"
      }
    }
  </script>
</pre>

core/extra-webpack.config.js
<pre>
const singleSpaAngularWebpack = require('single-spa-angular/lib/webpack').default;
const SystemJSPublicPathWebpackPlugin = require('systemjs-webpack-interop/SystemJSPublicPathWebpackPlugin');

module.exports = (config, options) => {
  // config.output.jsonpFunction = '@mtcorp/core';

  const singleSpaWebpackConfig = singleSpaAngularWebpack(config, options);

  singleSpaWebpackConfig.plugins.push(new SystemJSPublicPathWebpackPlugin({
    // ONLY NEEDED FOR WEBPACK 1-4. Not necessary for webpack@5
    systemjsModuleName: '@mtcorp/core'
  }));

  // Feel free to modify this webpack config however you'd like to
  return singleSpaWebpackConfig;
};
</pre>

analise-compra/extra-webpack.config.js
<pre>
const singleSpaAngularWebpack = require('single-spa-angular/lib/webpack').default;

module.exports = (config, options) => {
  config.output.jsonpFunction = '@mtcorp/abastecimento/analise-compra';
  
  const singleSpaWebpackConfig = singleSpaAngularWebpack(config, options);

  singleSpaWebpackConfig.externals.push(
    '@mtcorp/core'
  );

  // Feel free to modify this webpack config however you'd like to
  return singleSpaWebpackConfig;
};
</pre>

<pre>
Libs:
- @angular/core version: 11.2.11
- single-spa-angular version: 4.9.2
</pre>

-----

My idea is to reuse modules of services/pipes/etc exported by core in the child applications, but as I said I'm having the error generated when running "npm run serve" in the application "analise-compras".

Could someone help me to tell me what is wrong or missing?

Thanks for the advance

**Comment by orosro** [comment]
I think you need to install the dependency when using it, even if it's declared as an external one.  How is the "core" lib packaged? And is it an actual library or an angular application? The library, or better said the package that you want to use as external, should export the module. I don't think the bundle generated by Angular is exporting the modules like a normal library inside the index.js file, or even if it's exporting the  modules. 

What I did was to create separate libraries/services that are packed as npm module and published on the internal npm registry & at the same time, the bundle is published on the server from where we retrieve it  at runtime.  The package is installed on the application I want to use it, so that we have access to anything that it offers, including typing. (Cool part is that it works in standalone mode as well), declare it as external, the app compiles successfully and it retrieves that package at runtime.

**Comment by llinq** [comment]
Thanks man!

Undestand, I was exporting an angular application and trying to import a module from it as you mentioned, it wouldn't really work.

I managed to go forward, I created an angular library where the reusable modules will be, but I'm still having the same error.

I think I reached point X, about the npm library, is it mandatory to work, or in the beginning I can go ahead without it to go testing locally? I ask this because even after creating a library project and exporting it in importmap, angular apparently can't build the app because it doesn't find the reference "@mtcorp/shared".

This is the repository: https://github.com/llinq/testing-single-spa-angular

**Comment by orosro** [comment]
Yes,  you need to install the library inside your project. 
Just for testing purposes, you can always pack the library locally using "npm pack".  
You can read articles such as: https://www.tsmean.com/articles/how-to-write-a-typescript-library/ in order to get a better understanding over how to create libraries & use npm pack. 

It seems as an overhead at first but it's something you only do once
Set up the library pipeline at first
Install the shared package inside the application you want to use.

**Comment by llinq** [comment]
Alright, thanks for the help, I'll proceed
