### ISSUE TITLE
Two angular applications with two different NGRX states

### ISSUE THREAD

**Issue by CristianVallecchia** [single-spa/single-spa-angular#414]
**Describe the bug or question**
Is it possible to have two angular applications with two different ngrx states that can be consulted on the redux browser console?

**To Reproduce**
1 root +  2 angular app with ngrx.

**Expected behavior**
I have two angular applications with ngrx, the featureKeys are different, but on the browser console I only display the status of a single application

**Comment by arturovt** [comment]
Well, I don't think there are any pitfalls on having NgRx states in different apps. I don't have time to reproduce it locally, you can clone this repository, we have integration apps, you can install `@ngrx/store` and check if there're any issues.

I'm also not sure what is meant in the "expected behavior" section, if you want to display logs only from a single application then just disable the plugin in another application.
