### ISSUE TITLE
Angular guard and cancelled navigations

### ISSUE THREAD

**Issue by lest54** [single-spa/single-spa-angular#434]
We have an issue with a single-spa/single-spa-angular and Angular where when multiple (thee in the demo repo below) applications coexist and share the same (or close enough) routing configuration and one of them protects one of the routes with a guard that performs an async operation, navigations are cancelled but only when initiated outside of the application that declares the guard.

### Demonstration

*STEPS TO REPRODUCE*

1. Clone repo https://github.com/lest54/coexisting-angular-microfrontends-master-1
2. execute npm install and npm run start in app1, app2, navbar and roothtmlfile folders
3. Navigate to http://localhost:4200/route/4
4. Click on [app 1 - route 1] link

### Expected Behavior
Application navigates to http://localhost:4200/route/1

### Actual Behavior

- Application navigates to http://localhost:4200/route/1 then immediately back to http://localhost:4200/route/4.
- Two NavicationCancel events are logged for /route/1
- If the guard (CanActivateTeam under app2) is removed or modified to return of(true) without a delay, it behaves as expected.

Has anyone run into this before? We've tested Angular 9 thru 12 with the different versions of single-spa-angular and they all behave the same way.

**Comment by bh3605** [comment]
Can you determine which app is causing the navigation cancel event to be thrown? I don't see any routes in any routing module that specifies a path of "/route". Knowing this I would say Angular is behaving as expected because it won't navigate to a route it doesn't recognize

**Comment by arturovt** [comment]
@lest54 I know the issue exists. The problem exists when _you don't share dependencies_. There're multiple location and router instances that conflict with each other. We tried to fix that issue with different approaches, but unfortunately, nothing can fix the problem (just because Angular router wasn't designed to work in a micro-frontend environment).

The only advice I can give you is to share dependencies. It's officially possible now with SystemJS since we host Angular packages in SystemJS format (see esm-bundle repo).

See this guide on how to accomplish this: https://single-spa.js.org/docs/ecosystem-angular/#shared-angular
