### ISSUE TITLE
Load static js file in index.ejs

### ISSUE THREAD

**Issue by youssefM95** [single-spa/single-spa-angular#454]
### Question
Hi
i'm trying to load js file in index.ejs instead of load it by url.
I created a new "assets" folder that contains the js files and I modified this line from :
<script src="https://unpkg.com/core-js-bundle/minified.js"></script> 
to :
<script src="./assets/js/minified.js"></script>
but always file not found 
![image](https://user-images.githubusercontent.com/26021197/187071942-b14c9e7f-8cfd-4f5a-ad7d-4eb2d93cff8c.png)
can someone help me 

### Environment

<pre><code>
Libs:
- webpack: 5.51.1
- webpack-cli: 4.8.0
- webpack-config-single-spa-ts: 4.0.0

</code></pre>

**Comment by filoxo** [comment]
This relates to how you deploy your assets publicly. That is outside of the scope of single-spa-angular because it is a client-side helper. 

However, it's really not that complicated. For one, do NOT use a relative URL. Specifically, the leading `./` in that URL is what makes it relative. 

maybe take a look at https://github.com/single-spa/self-hosted-shared-dependencies for helping you get assets to self-host them, and then you provide the mechanism to make them available to the web. But the actual deployment is not something that we can offer help with because that is not within our domain.
