### ISSUE TITLE
Angular 6 shared assets and fonts 

### ISSUE THREAD

**Issue by brx-anton** [single-spa/single-spa-angular#459]
Greetings, we are changing our structure from default angular app to single spa. We inject our current project as a MFE in root config as a default route for now.
The project is using Angular 6 so we build it using `single-spa-angular:build` without Webpack.
That means that we don't have a `webpack_public_path` to use AssetURL and Pipe. Also we would like to less on refactoring as much as possible since we have import images in ts, html, scss formats. The same thing is related to sharing fonts.
Question is:
How can we share assets with the least code changes? Or should we just move them to the root config and serve there? Or there are some workarounds?

Libs:
- @angular/core version: 6.1.10
- single-spa-angular version: 3.6.0

**Comment by arturovt** [comment]
I ain't sure I can answer the question since it's not strictly related to Angular. I should emphasize that single-spa-angular drops support Angular versions that have been deprecated or deprecated long ago. So using Angular 6 is off the supported path. Try re-opening the issue in the single-spa repository, but w/o tying to Angular. The question is more general and might be related to any framework.
