### ISSUE TITLE
Navigation triggered outside Angular zone

### ISSUE THREAD

**Issue by gubertcalixto** [single-spa/single-spa-angular#53]
Using Angular 7 Apps, when any <a routerLink> is clicked, the following message (console.warn) shows:
**Navigation triggered outside Angular zone, did you forget to call 'ngZone.run()**

![image](https://user-images.githubusercontent.com/28396856/55909405-4ddac500-5bb2-11e9-856f-ea7ed8694f78.png)

**Comment by jlewicki-nevo** [comment]
I see this as well.

It appears to me that there may be a problem with the monkey-patched isInAngularZone.  

single-spa-angular sticks a boolean in the zone properties [here](https://github.com/CanopyTax/single-spa-angular/blob/64a09b87a621b7b4a8c244fe184f5d2e5a8ceead/src/browser-lib/single-spa-angular.ts#L80) but implements isInAngularZone by checking for a string [here](https://github.com/CanopyTax/single-spa-angular/blob/64a09b87a621b7b4a8c244fe184f5d2e5a8ceead/src/browser-lib/single-spa-angular.ts#L53)

The string/boolean comparison fails, so the angular router thinks it is outside of a zone.

**Comment by joeldenning** [comment]
@jlewicki-nevo thanks for your PR -- **it fixes some but not all of the navigation related warnings**. Your change was released in [single-spa@3.0.0-beta.20](https://github.com/CanopyTax/single-spa-angular/releases/tag/v3.0.0-beta.20).

Here's why the change didn't completely getting rid of the console.warning(), and why doing so will be tricky:

Angular router assumes that it is the only router on the page. However, in the case of single-spa-angular, there is **one router per single-spa application**. Doing so is something that works completely fine in browsers and has worked very well for all of the single-spa users (react, angular, vue, etc).

A router is something that 1) listens to [popstate events](https://developer.mozilla.org/en-US/docs/Web/API/Window/popstate_event), 2) listens to [hashchange events](https://developer.mozilla.org/en-US/docs/Web/API/Window/hashchange_event), and 3) implements a wrapper function around [history.pushState()](https://developer.mozilla.org/en-US/docs/Web/API/History_API). All three of those things are so that it knows when to reroute/rerender.

In @angular/router's case, it does the console warning whenever 1), 2), or 3) happens outside of the **zone for its angular application**. Since there are multiple instances of @angular/router on the page, this is a faulty assumption, since some routing is happening in different zones, by different angular applications.

I looked into this ^^ a week ago or so and think the only way to completely remove the warning would be to either 1) PR @angular/router to not assume it's the only thing doing routing, or 2) monkey patch the console.warn() function so that it ignores that particular warning. Option 1 is a lot of work and I feel like it would likely be rejected with a "don't do that you don't know what you're doing and that's really bad" comment. Option 2 is very very hacky and doesn't feel great.

I'm very open to other options besides the ones I've listed. Since we're talking about a console warning, this issue isn't my highest priority one right now, since there are other issues that are resulting in actual bugs. I'm reopening this issue in case others have ideas for how to fix this or for the ambitious soul who wants to attempt Option 1.

**Comment by arturovt** [comment]
Currently, I'd say that this is normal behaviour. In Angular 4-8 initial navigation is physically done outside of the Angular zone, because it's done by _single-spa_, but other navigations do not cause these warnings, this was fixed in multiple PRs some days.
